application: dilbert-search
version: 1
runtime: python
api_version: 1

handlers:
- url: /a/(.*)
  static_files: a/\1
  upload: a/(.*)
  expiration: "1d"

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /\d+/\d+\.gif
  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /.*
  script: dilbert.py
