application: dilbert-search
version: 1
runtime: python
api_version: 1

handlers:
- url: /a/(.*)
  static_files: a/\1
  upload: a/(.*)

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: dilbert.py
